workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.lamasparsha.merorider"
        GRADLE_OPTS: "-Xmx3072m"
        JAVA_TOOL_OPTIONS: "-Xmx3072m"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
        - pattern: develop
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk \
            --release \
            --build-number=$(($(date +%s) / 60))
      - name: Build AAB
        script: |
          flutter build appbundle \
            --release \
            --build-number=$(($(date +%s) / 60))
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:

      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        BUNDLE_ID: "com.lamasparsha.merorider"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        XCODE_PROJECT: "ios/Runner.xcodeproj"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
        - pattern: develop
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd ios && pod install --repo-update && cd ..
      - name: Build iOS app
        script: |
          flutter build ios \
            --release \
            --no-codesign
      - name: Build iOS Simulator App
        script: |
          flutter build ios --debug --simulator
          cd build/ios/iphonesimulator && zip -r Runner.app.zip Runner.app
      - name: Package for App Store
        script: |
          cd ios
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -derivedDataPath build/ios_build \
            -allowProvisioningUpdates \
            build-for-testing
          cd ..
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphonesimulator/Runner.app.zip
      - ios/build/ios_build/**/*.ipa
    publishing:

      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true

  full-workflow:
    name: Full Build (Android + iOS)
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.lamasparsha.merorider"
        BUNDLE_ID: "com.lamasparsha.merorider"
        GRADLE_OPTS: "-Xmx3072m"
        JAVA_TOOL_OPTIONS: "-Xmx3072m"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build Android APK
        script: |
          flutter build apk \
            --release \
            --build-number=$(($(date +%s) / 60))
      - name: Build Android AAB
        script: |
          flutter build appbundle \
            --release \
            --build-number=$(($(date +%s) / 60))
      - name: Install iOS pods
        script: |
          cd ios && pod install --repo-update && cd ..
      - name: Build iOS app
        script: |
          flutter build ios \
            --release \
            --no-codesign
      - name: Build iOS Simulator App
        script: |
          flutter build ios --debug --simulator
          cd build/ios/iphonesimulator && zip -r Runner.app.zip Runner.app
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/iphoneos/Runner.app
      - build/ios/iphonesimulator/Runner.app.zip
    publishing:

      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true